print("At 6:20AM I wake up for school")
print("At 6:21AM I go to brush my teeth")
print("At 6:23AM I go to take a shower")
print("At 6:35AM I wear my uniform")
print("At 7:00AM i go downstairs and leave for school")
print("At 2:00PM I come back from school and eat lunch")
print("At 3:30pm i leave for classes")
print("i have dinner at 8:00pm")
print("I sleep at 12:20am")